id: IBEE104A7
legacy_id: P010751
ocr_import_info:
  bdrc_scan_id: W30135
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T09:10:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:19:24.974259+00:00'
last_modified: 2022-09-03 19:19:47.896771
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30135
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW30135
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསོ་རིག་བསྟན་བཅོས་མཐའ་དག་གི་སྙིང་པོ་རྣམས་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པ་མན་ངག་རིན་ཆེན་འབྱུང་གནས།
  author: བཙན་པོ་ནོ་མིན་ཧན ༠༤་འཇམ་དཔལ་ཆོས་ཀྱི་བསྟན་འཛིན་འཕྲིན་ལས།
statistics:
  ocr_word_mean_confidence_index: 0.6408460570510186
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I5908:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5908
      total_pages: 748
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5908.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6408460570510186
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
