id: IBEE104A7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T09:15:26+00:00'
last_modified: '2022-06-08T17:15:53.208872+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30135
  title: གསོ་རིག་བསྟན་བཅོས་མཐའ་དག་གི་སྙིང་པོ་རྣམས་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པ་མན་ངག་རིན་ཆེན་འབྱུང་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    52F9:
      image_group_id: I5908
      title: ''
      total_pages: 748
      order: 1
      base_file: 52F9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
